version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0
    groups:
      prisma:
        patterns:
          - '@prisma/*'
          - 'prisma'
      tanstack:
        patterns:
          - '@tanstack/*'
      types:
        patterns:
          - '@types/*'
        dependency-type: 'development'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0
