[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm prisma generate', 'pnpm build']

[start]
cmd = 'sh -c "pnpm prisma migrate deploy && pnpm db:seed && pnpm start"'
